# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7dbd710c97a7d91deb71ba7bd1d3f561982c6b9a271bf65319cd489170201b6d3bb9fcb3212218c41f6e19e8ecd4a02b877a3bf087dc61bf0a85fdef077ed8f0

test:
  secret_key_base: 3806f73392a72011bce0ea06d77f644ebe523bc7930086bbf90f04579f6289879ee838b1316852880d6f268a95ab25457fcfdc227109737049cf4fee6e83fc58

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
